version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    image: sports-app:development
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $username
      POSTGRES_DB: $database
      POSTGRES_PASSWORD: $password
    
volumes:
  pg-dev-data: