version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    image: sports-app:production
    volumes:
      - .:/app
    ports:
      - 3010:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pg-prod-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $PROD_USERNAME
      POSTGRES_DB: $PROD_DATABASE
      POSTGRES_PASSWORD: $PROD_PASSWORD
    
volumes:
  pg-prod-data:
