name: Auto test solution
on: push
env:
  PG_DATABASE: wd-sports-test2
  PG_USER: postgres
  PG_PASSWORD: chinni06
jobs:
  # Label of the container job
  run-tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:11.7
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: chinni06
          POSTGRES_DB: wd-sports-test2
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: cd sports-sch2 && npm ci

      - name: Run unit tests
        run: cd sports-sch2 && npm test
      - name: Run the app
        id: run-app
        run: |
          cd sports-sch2
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3500 npm run clean:start &
          sleep 5

      - name: Run integration tests
        run: |
          cd sports-sch2
          npm install cypress cypress-json-results
          npx cypress run
